2023-08-13 16:51:39,516 - ERROR - Excepción no capturada:
Traceback (most recent call last):
  File "C:\Users\svcmerr\Desktop\pw\Conciliacion\run.py", line 12, in <module>
    menu_opciones.login()
  File "C:\Users\svcmerr\Desktop\pw\Conciliacion\menu_opciones.py", line 17, in login
    if  user_entry.get() == "admin" and password_entry.get() == "1234":
        ^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\tkinter\__init__.py", line 3109, in get
    return self.tk.call(self._w, 'get')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_tkinter.TclError: invalid command name ".!entry"
2023-08-13 18:32:21,552 - ERROR - Excepción no capturada:
Traceback (most recent call last):
  File "C:\Users\svcmerr\Desktop\pw\Conciliacion\run.py", line 12, in <module>
    menu_opciones.login()
  File "C:\Users\svcmerr\Desktop\pw\Conciliacion\menu_opciones.py", line 18, in login
    if  user_entry.get() == "admin" and password_entry.get() == "1234":
        ^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\tkinter\__init__.py", line 3109, in get
    return self.tk.call(self._w, 'get')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_tkinter.TclError: invalid command name ".!entry"
2023-08-13 18:33:26,935 - ERROR - Excepción no capturada:
Traceback (most recent call last):
  File "C:\Users\svcmerr\Desktop\pw\Conciliacion\run.py", line 12, in <module>
    menu_opciones.login()
  File "C:\Users\svcmerr\Desktop\pw\Conciliacion\menu_opciones.py", line 18, in login
    if  user_entry.get() == "admin" and password_entry.get() == "1234":
        ^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\tkinter\__init__.py", line 3109, in get
    return self.tk.call(self._w, 'get')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_tkinter.TclError: invalid command name ".!entry"
2023-08-13 18:35:13,040 - ERROR - Excepción no capturada:
Traceback (most recent call last):
  File "C:\Users\svcmerr\Desktop\pw\Conciliacion\run.py", line 12, in <module>
    menu_opciones.login()
  File "C:\Users\svcmerr\Desktop\pw\Conciliacion\menu_opciones.py", line 18, in login
    if  user_entry.get() == "admin" and password_entry.get() == "1234":
        ^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\tkinter\__init__.py", line 3109, in get
    return self.tk.call(self._w, 'get')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_tkinter.TclError: invalid command name ".!entry"
